name: Docker Publish

on:
  push:
    tags:
      - "v*"

jobs:
  docker-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    environment: production
    env:
      COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
      COSIGN_KEY: ${{ secrets.COSIGN_KEY }}
      REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
      REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
      REGISTRY_ADDRESS: ${{ vars.REGISTRY_ADDRESS }}
      PUBLISH_ADDRESS: ${{ vars.PUBLISH_ADDRESS }}
      TAG: ${{ github.ref_name }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Call Docker-Publish Function
        uses: dagger/dagger-for-github@v6.13.0
        with:
          version: "latest"
          verb: call
          args: "publish-image --cosign-password='env:${{ env.COSIGN_PASSWORD }}' --cosign-key='env:${{ env.COSIGN_KEY }}' --reg-username='${{ env.REGISTRY_USERNAME }}' --reg-password='env:${{ env.REGISTRY_PASSWORD }}' --reg-address='${{ env.REGISTRY_ADDRESS }}' --publish-address='${{ env.PUBLISH_ADDRESS }}' --tag='${{ env.TAG }}'"
