name: Docker Publish

on:
  release:
    types: [published]
  push:
    tags:
      - "v*"

jobs:
  docker-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Call Docker-Publish Function
        uses: dagger/dagger-for-github@v6.13.0
        with:
          version: "latest"
          verb: call
          args: publish-image --source=. --cosign-key=${{ secrets.COSIGN_KEY }} --cosign-password=${{ env.COSIGN_PASSWORD }}  --reg-username=${{ env.REGISTRY_USERNAME }}  --reg-password=${{ env.REGISTRY_PASSWORD }}
