name: Dagger Release Pipeline

on:
  push:
    tags:
      - "v*"
    branches: [main]

permissions:
  contents: write
  packages: write

jobs:
  publish-release:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Call Dagger Function
        uses: dagger/dagger-for-github@v6.13.0
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          version: "latest"
          verb: call
          args: release --github-token='env:${{ env.GITHUB_TOKEN }}'